# Generated by Django 3.0.2 on 2020-11-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('blog', '0004_blog_field1'), ('blog', '0005_blog_field2')]

    dependencies = [
        ('blog', '0003_auto_20201117_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='field1',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='blog',
            name='field2',
            field=models.CharField(default='', max_length=250),
        ),
    ]
