# Generated by Django 3.0.2 on 2020-11-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_field1_squashed_0005_blog_field2'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='field3',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='blog',
            name='field4',
            field=models.CharField(default='', max_length=250),
        ),
    ]
