# Generated by Django 3.0.2 on 2020-11-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201126_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='field6',
            field=models.CharField(default='', max_length=250),
        ),
    ]
