# Generated by Django 3.0.2 on 2020-11-26 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_field6'),
        ('blog', '0006_blog_field5'),
    ]

    operations = [
    ]
